lib/chirper_web/router.ex
defmodule ChirperWeb.Router do
  use ChirperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChirperWeb do
    pipe_through :browser
    pipe_through ChirperWeb.Plugs.Guest

    resources "/register", UserController, only: [:create, :new]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end


  scope "/", ChirperWeb do
    pipe_through :browser
    pipe_through ChirperWeb.Plugs.Auth

    delete "/logout", SessionController, :delete


    get "/", PostController, :index
    get "/show", PageController, :show
    resources "/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChirperWeb do
  #   pipe_through :api
  # end
end

lib/chirper_web/views/layout_view.ex
defmodule ChirperWeb.LayoutView do
  use ChirperWeb, :view
end

lib/chirper_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CHIRPER</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper primary-dark-color">
        <a href="/" class="brand-logo">CHIRPER</a>
     
        <!-- Dropdown Structure User actions -->
        <ul id="user-actions" class="dropdown-content">
          <li><%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %></li>
        </ul>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <%= if signed_in?(@conn) do %>
              <li><%= link "New Post", to: Routes.post_path(@conn, :new) %></li>
              <li><a class="dropdown-trigger" href="#!" data-target="user-actions"> <%= @current_user.username %> <i class="material-icons right">arrow_drop_down</i></a></li>
            <% else %>
              <%# <%= link "Login", to: Routes.session_path(@conn, :new) %>
            <% end %>
        </ul>
      </div>
    </nav>

    <main>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <div class='container'>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>

    <footer class="page-footer secondary-color">
      <div class="footer-copyright secondary-color">
        <div class="container">
          © 2014 Copyright Text
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    </body>
  </html>
        