lib/chirper_web/router.ex
defmodule ChirperWeb.Router do
  use ChirperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChirperWeb do
    pipe_through :browser
    pipe_through ChirperWeb.Plugs.Guest

    resources "/register", UserController, only: [:create, :new]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end


  scope "/", ChirperWeb do
    pipe_through :browser
    pipe_through ChirperWeb.Plugs.Auth

    delete "/logout", SessionController, :delete


    get "/", PostController, :index
    get "/show", PageController, :show
    resources "/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChirperWeb do
  #   pipe_through :api
  # end
end

lib/chirper/accounts/user.ex
defmodule Chirper.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Chirper.Accounts.{User, Encryption}
  alias Chirper.Blog.Post

  schema "users" do
    field :encrypted_password, :string
    field :username, :string

    # VIRTUAL FIELDS
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    has_many :posts, Post

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:username, :password])
    |> validate_required([:username])
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password)
    |> unique_constraint(:username)
    |> downcase_username
    |> encrypt_password
  end

  defp encrypt_password(changeset) do
    password = get_change(changeset, :password)
    if password do
      encrypted_password = Encryption.hash_password(password)
      put_change(changeset, :encrypted_password, encrypted_password)
    else
      changeset
    end
  end

  defp downcase_username(changeset) do
    update_change(changeset, :username, &String.downcase/1)
  end
end

lib/chirper_web/controllers/user_controller.ex
defmodule ChirperWeb.UserController do
  use ChirperWeb, :controller

  alias Chirper.Accounts
  alias Chirper.Accounts.User

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "Signed up successfully.")
        |> redirect(to: Routes.page_path(conn, :show))
    {:error, %Ecto.Changeset{} = changeset} ->
      render(conn, "new.html", changeset: changeset)
    end
  end

end

lib/chirper_web/views/user_view.ex
defmodule ChirperWeb.UserView do
  use ChirperWeb, :view
end

lib/chirper_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/chirper_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :username, placeholder: "Username" %>
  <%= error_tag f, :username %>

  <%= password_input f, :password, placeholder: "Password" %>
  <%= error_tag f, :password %>

  <%= password_input f, :password_confirmation, placeholder: "Confirm Password" %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Submit", class: "btn right secondary-color" %>
  </div>
<% end %>

lib/chirper_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Encrypted password</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.encrypted_password %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/chirper_web/templates/user/new.html.eex
<div class='row'>
  <div class='col s12 m6 offset-m3'>
    <div class='card'>
      <div class='card-content'>
        <span class='card-title'>REGISTER</span>
        <div class='row card-form'>

            <%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

            <%= link "Login", to: Routes.session_path(@conn, :new), class: "btn secondary-color" %>
        
        </div>
      </div>
    </div>
  </div>
</div>

lib/chirper_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Encrypted password:</strong>
    <%= @user.encrypted_password %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>